# Generated by Django 3.2.5 on 2021-07-29 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='point',
            old_name='closetdistance',
            new_name='closetpointpair',
        ),
    ]
