# Generated by Django 3.2.5 on 2021-07-29 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_rename_closetdistance_point_closetpointpair'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='computed',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
