# Generated by Django 3.2.5 on 2021-07-29 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_point_computed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='computed',
        ),
    ]
