# Generated by Django 3.2.5 on 2021-07-29 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0004_remove_point_computed'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='closetdistance',
            field=models.CharField(default=2121, max_length=200),
            preserve_default=False,
        ),
    ]
